#ifndef __QWORDVM_H__
#define __QWORDVM_H_

#include <stddef.h>
#include <stdint.h>

enum { QWORDVM_ARGS_MAX = 6 };

enum qwordvm_opcode {
    QWORDVM_OPCODE_NOP,
    QWORDVM_OPCODE_PUSH8,
    QWORDVM_OPCODE_PUSH16,
    QWORDVM_OPCODE_PUSH32,
    QWORDVM_OPCODE_PUSH64,
    QWORDVM_OPCODE_ADD,
    QWORDVM_OPCODE_SUB,
    QWORDVM_OPCODE_MUL,
    QWORDVM_OPCODE_DIV,
    QWORDVM_OPCODE_REM,
    QWORDVM_OPCODE_LT,
    QWORDVM_OPCODE_LE,
    QWORDVM_OPCODE_EQ,
    QWORDVM_OPCODE_NE,
    QWORDVM_OPCODE_GT,
    QWORDVM_OPCODE_GE,
    QWORDVM_OPCODE_AND,
    QWORDVM_OPCODE_OR,
    QWORDVM_OPCODE_NOT,
    QWORDVM_OPCODE_BAND,
    QWORDVM_OPCODE_BOR,
    QWORDVM_OPCODE_BSHL,
    QWORDVM_OPCODE_BSHR,
    QWORDVM_OPCODE_BNOT,
    QWORDVM_OPCODE_BXOR,
    QWORDVM_OPCODE_PEEK8,
    QWORDVM_OPCODE_PEEK16,
    QWORDVM_OPCODE_PEEK32,
    QWORDVM_OPCODE_PEEK64,
    QWORDVM_OPCODE_POKE8,
    QWORDVM_OPCODE_POKE16,
    QWORDVM_OPCODE_POKE32,
    QWORDVM_OPCODE_POKE64,
    QWORDVM_OPCODE_SWAP,
    QWORDVM_OPCODE_DUP,
    QWORDVM_OPCODE_JMP,
    QWORDVM_OPCODE_JMPC,
    QWORDVM_OPCODE_SYSCALL,
    QWORDVM_OPCODE_HALT
};

enum qwordvm_error {
    QWORDVM_INVALID_VERSION = -1,
    QWORDVM_SUCCESS = 0,
    QWORDVM_ERROR_STACK_OVERFLOW,
    QWORDVM_ERROR_STACK_UNDERFLOW,
    QWORDVM_ERROR_CODE_OUT_OF_BOUNDS,
    QWORDVM_ERROR_DIVISION_BY_ZERO,
    QWORDVM_ERROR_INVALID_SYSCALL,
    QWORDVM_ERROR_UNKNOWN_INSTRUCTION,
    QWORDVM_ERROR_INVALID_PEEK,
    QWORDVM_ERROR_INVALID_POKE,
    QWORDVM_ERROR_INVALID_CODE,
    QWORDVM_ERROR_INVALID_STACK,
    QWORDVM_ERROR_TOO_MANY_ARGUMENTS,
    QWORDVM_ERROR_UNKNOWN_SYSCALL,
};

#endif